/**
 * Hardcoded sports fixture data — ported verbatim from sport.html.
 *
 * In the legacy site this was generated by an external script and inlined
 * into sport.html. There is no /api/sport endpoint yet, so this list is
 * the source of truth in the React rewrite. Replace it with a real fetch
 * (e.g. /api/sport) when the backend gains an endpoint for it.
 */

export type SportCategory = 'cross_country' | 'biathlon' | 'football';
export type SourceKey = 'NRK' | 'TV 2' | 'Viaplay' | 'NRK Radio' | 'TWE';

export interface SportEvent {
  idx: number;
  title: string;
  category: SportCategory;
  channel: string;
  date: string; // YYYY-MM-DD
  startTime: string; // HH:MM
  /** Unix seconds. */
  timestamp: number;
  streamUrl?: string;
  radioUrl?: string;
  competition?: 'UCL' | 'PL' | 'LL';
}

export interface SourceInfo {
  label: string;
  url: string | null;
  cls: string;
}

export const SPORT_DATA: { events: SportEvent[]; lastUpdated: string } = {
  lastUpdated: 'Tirsdag 24. mars 2026 · 11:07',
  events: [
    { idx: 0,  title: 'NM på ski: Lagsprint, kvalifisering',          category: 'cross_country', channel: 'TV 2', date: '2026-03-27', startTime: '15:40', timestamp: 1774622400, streamUrl: 'https://play.tv2.no/sport/vintersport/langrenn/nm-langrenn-p6wncffb/sprintstafett-prolog-kvinner-og-menn-4mw48bpq' },
    { idx: 1,  title: 'NM på ski: Lagsprint, finaler',                category: 'cross_country', channel: 'TV 2', date: '2026-03-27', startTime: '17:00', timestamp: 1774627200, streamUrl: 'https://play.tv2.no/sport/vintersport/langrenn/nm-langrenn-p6wncffb/sprintstafett-finaler-kvinner-og-menn-ke1s0m3f' },
    { idx: 2,  title: 'Ski Classics, Reistadløpet',                    category: 'cross_country', channel: 'NRK',  date: '2026-03-28', startTime: '09:55', timestamp: 1774688100, streamUrl: 'https://tv.nrk.no/program/ISPO30261126' },
    { idx: 3,  title: 'NM på ski: 5 kilometer, kvinner',               category: 'cross_country', channel: 'TV 2', date: '2026-03-28', startTime: '12:00', timestamp: 1774695600, streamUrl: 'https://play.tv2.no/sport/vintersport/langrenn/nm-langrenn-p6wncffb/5-km-kvinner-4rakqkym' },
    { idx: 4,  title: 'NM på ski: 10 kilometer, menn',                 category: 'cross_country', channel: 'TV 2', date: '2026-03-28', startTime: '14:00', timestamp: 1774702800, streamUrl: 'https://play.tv2.no/sport/vintersport/langrenn/nm-langrenn-p6wncffb/10-km-menn-rennstart-n3mdtyxe' },
    { idx: 5,  title: 'Ski Classics, Summit 2 Senja',                  category: 'cross_country', channel: 'NRK',  date: '2026-03-29', startTime: '07:25', timestamp: 1774765500, streamUrl: 'https://tv.nrk.no/program/ISPO30261226' },
    { idx: 6,  title: 'NM på ski, 30 kilometer, kvinner',              category: 'cross_country', channel: 'TV 2', date: '2026-03-29', startTime: '11:10', timestamp: 1774775400, streamUrl: 'https://play.tv2.no/sport/vintersport/langrenn/nm-langrenn-p6wncffb/30-km-kvinner-rennstart-p9taxhg5' },
    { idx: 7,  title: 'NM på ski, 50 kilometer, menn',                 category: 'cross_country', channel: 'TV 2', date: '2026-03-29', startTime: '13:15', timestamp: 1774782900 },
    { idx: 8,  title: 'Real Madrid CF vs FC Bayern München — kvartfinale', category: 'football', channel: 'TV 2', date: '2026-04-07', startTime: '21:00', timestamp: 1775581200, competition: 'UCL', streamUrl: 'https://play.tv2.no/sport/fotball/uefa-champions-league-rbxjhx5m/' },
    { idx: 9,  title: 'Sporting Clube de Portugal vs Arsenal FC — kvartfinale', category: 'football', channel: 'TV 2', date: '2026-04-07', startTime: '21:00', timestamp: 1775581200, competition: 'UCL', streamUrl: 'https://play.tv2.no/sport/fotball/uefa-champions-league-rbxjhx5m/' },
    { idx: 10, title: 'Paris Saint-Germain FC vs Liverpool FC — kvartfinale', category: 'football', channel: 'TV 2', date: '2026-04-08', startTime: '21:00', timestamp: 1775667600, competition: 'UCL', streamUrl: 'https://play.tv2.no/sport/fotball/uefa-champions-league-rbxjhx5m/' },
    { idx: 11, title: 'FC Barcelona vs Club Atlético de Madrid — kvartfinale', category: 'football', channel: 'TV 2', date: '2026-04-08', startTime: '21:00', timestamp: 1775667600, competition: 'UCL', streamUrl: 'https://play.tv2.no/sport/fotball/uefa-champions-league-rbxjhx5m/' },
    { idx: 12, title: 'NM skiskyting, fellesstart, kvinner',           category: 'biathlon', channel: 'NRK', date: '2026-04-11', startTime: '15:25', timestamp: 1775917500, streamUrl: 'https://tv.nrk.no/program/ISPO30300326' },
    { idx: 13, title: 'NM skiskyting, fellesstart, menn',              category: 'biathlon', channel: 'NRK', date: '2026-04-11', startTime: '16:25', timestamp: 1775921100, streamUrl: 'https://tv.nrk.no/program/ISPO30300426' },
    { idx: 14, title: 'NM skiskyting, stafett, kvinner',               category: 'biathlon', channel: 'NRK', date: '2026-04-12', startTime: '10:30', timestamp: 1775986200, streamUrl: 'https://tv.nrk.no/program/ISPO30300526' },
    { idx: 15, title: 'NM skiskyting, stafett, menn',                  category: 'biathlon', channel: 'NRK', date: '2026-04-12', startTime: '12:55', timestamp: 1775994900, streamUrl: 'https://tv.nrk.no/program/ISPO30300626' },
    { idx: 16, title: 'Liverpool FC vs Paris Saint-Germain FC — kvartfinale', category: 'football', channel: 'TV 2', date: '2026-04-14', startTime: '21:00', timestamp: 1776186000, competition: 'UCL', streamUrl: 'https://play.tv2.no/sport/fotball/uefa-champions-league-rbxjhx5m/' },
    { idx: 17, title: 'Club Atlético de Madrid vs FC Barcelona — kvartfinale', category: 'football', channel: 'TV 2', date: '2026-04-14', startTime: '21:00', timestamp: 1776186000, competition: 'UCL', streamUrl: 'https://play.tv2.no/sport/fotball/uefa-champions-league-rbxjhx5m/' },
    { idx: 18, title: 'FC Bayern München vs Real Madrid CF — kvartfinale', category: 'football', channel: 'TV 2', date: '2026-04-15', startTime: '21:00', timestamp: 1776272400, competition: 'UCL', streamUrl: 'https://play.tv2.no/sport/fotball/uefa-champions-league-rbxjhx5m/' },
    { idx: 19, title: 'Arsenal FC vs Sporting Clube de Portugal — kvartfinale', category: 'football', channel: 'TV 2', date: '2026-04-15', startTime: '21:00', timestamp: 1776272400, competition: 'UCL', streamUrl: 'https://play.tv2.no/sport/fotball/uefa-champions-league-rbxjhx5m/' },
    { idx: 20, title: 'Semifinale 1 (oppdateres)',                     category: 'football', channel: 'TV 2', date: '2026-04-28', startTime: '02:00', timestamp: 1777327200, competition: 'UCL', streamUrl: 'https://play.tv2.no/sport/fotball/uefa-champions-league-rbxjhx5m/' },
    { idx: 21, title: 'Semifinale 2 (oppdateres)',                     category: 'football', channel: 'TV 2', date: '2026-04-29', startTime: '02:00', timestamp: 1777413600, competition: 'UCL', streamUrl: 'https://play.tv2.no/sport/fotball/uefa-champions-league-rbxjhx5m/' },
    { idx: 22, title: 'Semifinale 3 (oppdateres)',                     category: 'football', channel: 'TV 2', date: '2026-05-05', startTime: '02:00', timestamp: 1777932000, competition: 'UCL', streamUrl: 'https://play.tv2.no/sport/fotball/uefa-champions-league-rbxjhx5m/' },
    { idx: 23, title: 'Semifinale 4 (oppdateres)',                     category: 'football', channel: 'TV 2', date: '2026-05-06', startTime: '02:00', timestamp: 1778018400, competition: 'UCL', streamUrl: 'https://play.tv2.no/sport/fotball/uefa-champions-league-rbxjhx5m/' },
    { idx: 24, title: 'Champions League — finale',                     category: 'football', channel: 'TV 2', date: '2026-05-30', startTime: '18:00', timestamp: 1780149600, competition: 'UCL', streamUrl: 'https://play.tv2.no/sport/fotball/uefa-champions-league-rbxjhx5m/' },
  ],
};

export const STREAMS: Record<SourceKey, SourceInfo> = {
  'NRK':       { label: 'NRK TV',          url: null,                                          cls: 'nrk' },
  'TV 2':      { label: 'TV 2 direkte',    url: 'https://tv2.no/direkte/',                    cls: 'tv2' },
  'Viaplay':   { label: 'Viaplay Sport',   url: 'https://viaplay.no/sport/live',              cls: 'viaplay' },
  'NRK Radio': { label: 'NRK Sport Radio', url: 'https://radio.nrk.no/direkte/sport',         cls: 'radio' },
  'TWE':       { label: 'TWE Langrenn',    url: 'https://twe.no/channelPlay/TnNo4034',        cls: 'twe' },
};

/** Returns the playable source list for an event (channel + cross-country auto-adds TWE). */
export function getSources(event: SportEvent): SourceKey[] {
  const sources = event.channel
    .split(' + ')
    .map((s) => s.trim())
    .filter((s): s is SourceKey => s in STREAMS);
  if (event.category === 'cross_country' && !sources.includes('TWE')) sources.push('TWE');
  return sources;
}

/** Resolves the URL to open for a given source on a given event. */
export function resolveUrl(source: SourceKey, event: SportEvent): string {
  if (source === 'NRK') return event.streamUrl ?? 'https://tv.nrk.no/sport';
  if (source === 'Viaplay') return event.streamUrl ?? STREAMS.Viaplay.url ?? '#';
  if (source === 'TV 2') return event.streamUrl ?? STREAMS['TV 2'].url ?? '#';
  if (source === 'NRK Radio') return event.radioUrl ?? STREAMS['NRK Radio'].url ?? '#';
  return STREAMS[source].url ?? '#';
}
